---

version: '3.8'

services:

############################
# RADARR
############################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/arr/radarr/config:/config
      - /media/arr/Movies:/movies 
      - /media/arr/qbittorrent/downloads:/downloads 
    restart: unless-stopped
    
############################
# SONARR
############################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/arr/sonarr/config:/config
      - /media/arr/Shows:/tv
      - /media/arr/qbittorrent/downloads:/downloads
    restart: unless-stopped
    
############################
# PROWLARR
############################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/arr/prowlarr/config:/config
    restart: unless-stopped

############################
# BAZARR
############################

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/arr/bazarr/config:/config
      - /media/arr/Movies:/movies 
      - /media/arr/Shows:/tv 
    restart: unless-stopped
    
############################
# LIDARR
############################

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/arr/lidarr/config:/config
      - /media/arr/Music:/music 
      - /media/arr/qbittorrent/downloads:/downloads 
    restart: unless-stopped
    
############################
# QBITTORRENT		
############################

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /media/arr/qbittorrent/config:/config
      - /media/arr/qbittorrent/downloads:/downloads
    restart: unless-stopped
    
############################
# GLUETUN
############################

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    ports:
      - 9696:9696 #prowlarr
      - 7878:7878 #radarr
      - 8989:8989 #sonarr
      - 6767:6767 #bazarr
      - 8686:8686 #lidarr
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn # or wireguard
      - OPENVPN_USER=<your vpn user>
      - OPENVPN_PASSWORD=<your vpn password>
      - SERVER_COUNTRIES=Netherlands
  restart: unless-stopped
      
############################
