#!/bin/bash
set -e

# Update APT package lists
sudo apt update

# Upgrade the packages that can be upgraded
sudo apt upgrade -y

# Perform a distribution upgrade
sudo apt dist-upgrade -y

# Remove unnecessary packages
sudo apt autoremove -y

# Clean up cached package files
sudo apt clean

# Update Flatpak packages
flatpak update -y
